---
- hosts: 172.31.17.166
  become: yes
  tasks:
  - include_tasks: myfiles.yml
  - name: i want to install webserver
    apt:
      name: apache2
      state: present
    notify: restartwebserver

  - name: i want to copy static files in to ansible nodes side
    copy:
      src: mystaticfile.html
      dest: /var/www/html/index.html   
      notify: restartwebserver

  - name: i want to copy dynamic file in to ansible nodes side     
    template:
         src: myindex.j2
         dest: /var/www/html/index.html
    notify: restartwebserver     

  - name: i want to download files from remote(internet) in to nodes side
    get_url:
      url: https://get.jenkins.io/war-stable/2.387.2/jenkins.war
      dest: /home/ubuntu/jenkins.war
      force_basic_auth: yes
    notify: restartwebserver

  - name: i want to create a folder 
    file:
      path: /home/ubuntu/myfolder
      state: directory

  
  handlers:
   - name: restartwebserver
     service:
        name: apache2
        state: restarted

