---
- hosts: 172.31.17.166
  become: yes
  tasks:
  - name: install git
    apt: 
      name: git
      state: present

  - name: install tree
    apt:
      name: tree
      state: present

  - name:
    apt:
      name: wget
      state: present
         
