---
- hosts: all
  become: yes
  tasks:
    - name: install webservers
      apt: 
        name: "{{mywebpackonubuntu}}"
        state: present
    - name: i want to start apache2
      service:
        name: "{{mywebpackonubuntu}}"
        state: restarted

    - name: install tree
      apt:
        name: tree
        state: present
        
    - name: i want to install webserver on RedHat nodes
      yum:
        name: httpd
        state: present
        when: ansible_os_family =="{mywebpackonRedHat}" 

    - name: i want to start webserver
      service:
        name: httpd
        state: started
        when: ansible_os_family =="RedHat"    
