---
- hosts:
  become: yes
  tasks:
  - name: i want to install apache2
    apt:
      name: apache2
      state: present
  - name: Update repositories cache and install "foo" package
  ansible.builtin.apt:
    name: foo
    update_cache: yes


