---
- hosts: mywebservers
  become: yes
  tasks:
    - name: install webservers
      apt: 
        name: "{{mywebpackonubuntu}}"
        state: present
        when: ansible_os_family =="Debian"

    - name: i want to start apache2
      service:
        name: "{{mywebpackonubuntu}}"
        state: restarted
        when: ansible_os_family =="Debian"

    - name: install tree
      apt:
        name: tree
        state: present
        
    - name: i want to install webserver on RedHat nodes
      yum:
        name: "{{mywebpackonRedHat}}"
        state: present
        when: ansible_os_family =="RedHat" 

    - name: i want to start webserver
      service:
        name: "{{mywebpackonRedHat}}"
        state: started
        when: ansible_os_family =="RedHat"    
